env:
  browser: true
  es2021: true
  node: true
  shared-node-browser: true
  jest: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/typescript'
  - 'prettier'
globals:
  __DEV__: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    impliedStrict: true
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
  - jest
  - import
rules:
  # built-in
  camelcase: 2
  no-unused-vars: 0
  no-console: 2
  semi: 0
  no-await-in-loop: 2
  no-shadow: 2  

  # react hooks
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1

  # react
  react/prop-types: 0
  react/no-danger: 2
  react/no-deprecated: 2

  # typescript
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/explicit-function-return-type':
    - 1
    - allowExpressions: true
  '@typescript-eslint/no-unused-vars':
    - 2
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: ^_
  '@typescript-eslint/member-delimiter-style': 0

  # import
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - - parent
          - sibling
      pathGroups:
        - pattern: '*.scss'
          group: index
          position: after
          patternOptions:
            matchBase: true
  import/no-useless-path-segments: 2

  no-restricted-imports:
    - error
    - patterns:
        - lodash.*
      paths:
        - lodash

overrides:
  - files:
      - '**/*.test.ts'
      - '**/*.test.tsx'
    rules:
      '@typescript-eslint/no-magic-numbers': 0
      '@typescript-eslint/no-non-null-assertion': 0
      '@typescript-eslint/no-explicit-any': 0
      no-await-in-loop: 0
      jest/consistent-test-it:
        - 2
        - fn: test
          withinDescribe: test
      jest/expect-expect: 2
      jest/no-disabled-tests: 2
      jest/no-commented-out-tests: 2

settings:
  react:
    version: '16.9.0'
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".ts"
      - ".tsx"
