name: npm-publish
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          fetch-depth: 0
      
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Set up GitHub Package Registry token
        run: |
          echo "//npm.pkg.github.com/:_authToken="$NPM_TOKEN >> .npmrc
          echo always-auth=true >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Packages
        run: npm install
      
      - name: Build and Publish
        run: |
            git config user.name crodriguezd
            git config user.email cdumar9@hotmail.com

            git pull origin master

            npm run build
            npm run release

            git push origin master --follow-tags --force

            npm publish

