name: Publish
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.npmrc'
      - '.github/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('npm.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Packages
        run: npm install
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: "@carlosdumar"
      - name: Install Packages
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


